### ISSUE TITLE
Whitespace in project path or file path

### ISSUE THREAD

**Issue by CreatureSurvive** [yonstorm/ProjectRider-Unity#1]
Having any whitespace in your project path will result in unity hanging upon import of this package. unity will infinitely watch for asset changes causing your validator to constantly loop.

after fixing this by removing whitespace in my project directory path I ran into another issue. if your project settings have a different project name than your project directory name, launching rider from unity will result in rider failing to find your project .sln file.

finally if there is any whitespace in the path to a file, double clicking to open it will result in rider failing to find the file.

I attempted to resolve this by editing `ProjectRider.OnAssetOpened()` `var completeAssetPath` to replace any whitespace in the path with `"\ "` such as you would in the terminal. that however was recognized as an invalid escape character in unity I also tried to replace it with `"*"` that didn't work either.

**Comment by yonstorm** [comment]
Thank you for your thorough explanation. It was easy to reproduce!

Fixed on c1dff1ed57a61af6ffb4e8f8de897aaf9a105f42
